# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      architecture: 'x64'

  - script: |
      sudo apt-get update
      sudo apt-get install libxml2-utils
      python -m pip install --upgrade pip setuptools wheel
      pip install -e .[test]
      pytest --pyargs wss_tools docs
    displayName: 'Run tests'

- job: 'PEP8'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0

  - script: |
      python -m pip install --upgrade pip setuptools
      pip install flake8
      flake8 wss_tools --count
    displayName: 'PEP 8 check'

- job: 'PEP517'
  pool:
    vmImage: 'Ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0

  - script: |
      python -m pip install --upgrade pip setuptools pep517 twine
      python -m pep517.build --source .
      twine check dist/*
    displayName: 'PEP 517 check'
